### ISSUE TITLE
Something wrong in iOS and Android

### ISSUE THREAD

**Issue by fh345392977** [solid-software/flutter_vlc_player#1]
When I run the examples code on iOS simulator, all the log is 
```
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
...(and repeats)
```

When it's on Android 8.0.0 (MI 6), the test URL is ok to play. But my camera rtsp will stop after 10 seconds.

What happens??

Beg for your reply.

**Comment by solid-software** [comment]
Hi @fh345392977 can you be more specific of your issue? Can you provide your camera rtsp URL? Detailed steps to reproduce?

**Comment by fh345392977** [comment]
On iOS, I can hear the sound of rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov, but no picture.

My camera rtsp URL is 'rtsp://192.168.1.254/xxx.mov'.

**Comment by solid-software** [comment]
Is there any public camera that we can access to test? Can you recheck also first URL - it seem to be malformed. Recently we updated plugin to include live stream - you can try to update and see if it works for you/help you in any way.

**Comment by fh345392977** [comment]
I'll try again.thx:tada:

**Comment by solid-software** [comment]
I don't think that those features you mentioned are supported. So there is only a way to create PR for now...
