### ISSUE TITLE
Failed to connect to RTSP server

### ISSUE THREAD

**Issue by jsgalarraga** [solid-software/flutter_vlc_player#118]
Trying to connect to a RTSP server in local network with URL: `rtsp://192.168.5.87:8554/cam`
I have a Linux machine running the server, which is working because I can visualize the streaming in other PC using VLC.
I tried running the app in the emulator and real device and none of them worked.
The URL provided in the example works fine.

My implementation:
```
VlcPlayer(
    aspectRatio: 16 / 9,
    url: 'rtsp://192.168.5.87:8554/cam',
    controller: controller,
    placeholder: Center(child: CircularProgressIndicator()),
    options: [
        '--quiet',
        '--no-drop-late-frames',
        '--no-skip-frames',
        '--rtsp-tcp'
    ]
)
```

The error output:
```
E/VLC     (12202): [0000007ec7c1c250/3266] libvlc demux: Failed to connect with rtsp://192.168.5.87:8554/cam
E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: Failed to connect to RTSP server 192.168.5.87:8554
E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: cannot connect to 192.168.5.87:8554
E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: Connection failed
E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: VLC could not connect to "192.168.5.87:8554".
E/VLC     (12202): [0000007ed0f98c90/3266] libvlc input: Your input can't be opened
E/VLC     (12202): [0000007ed0f98c90/3266] libvlc input: VLC is unable to open the MRL 'rtsp://192.168.5.87:8554/cam'. Check the log for details.
W/System.err(12202): (flutter_vlc_plugin) A VLC error occurred.
```

**Comment by jsgalarraga** [comment]
Problem was that the Android device is connected to the network via ethernet, and when enabling USB debugging and setting USB mode to device mode in developer options, ethernet stopped working for whatever reason.
Therefore there is no issue with the plugin

**Comment by Bi-Keyur-Tailor** [comment]
Hi, Having same issue can you please explain how did you assign url and option in VlcPlayer Widget. Thanks in advacne

**Comment by jsgalarraga** [comment]
@Bi-Keyur-Tailor in the first post is the implementation on how to set the url and the options

**Comment by andrewcapatina** [comment]
@jsgalarraga Did you end up getting this working in the emulator too? Sounds like the troubleshooting was done on the real device. I'm having trouble with emulator now. I can confirm my RTSP stream works with VLC, also I'm not seeing my server try to accept any sort of request, so I think I may face similar issue. 

Thanks.

**Comment by zatovagul** [comment]
> Trying to connect to a RTSP server in local network with URL: `rtsp://192.168.5.87:8554/cam` I have a Linux machine running the server, which is working because I can visualize the streaming in other PC using VLC. I tried running the app in the emulator and real device and none of them worked. The URL provided in the example works fine.
> 
> My implementation:
> 
> ```
> VlcPlayer(
>     aspectRatio: 16 / 9,
>     url: 'rtsp://192.168.5.87:8554/cam',
>     controller: controller,
>     placeholder: Center(child: CircularProgressIndicator()),
>     options: [
>         '--quiet',
>         '--no-drop-late-frames',
>         '--no-skip-frames',
>         '--rtsp-tcp'
>     ]
> )
> ```
> 
> The error output:
> 
> ```
> E/VLC     (12202): [0000007ec7c1c250/3266] libvlc demux: Failed to connect with rtsp://192.168.5.87:8554/cam
> E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: Failed to connect to RTSP server 192.168.5.87:8554
> E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: cannot connect to 192.168.5.87:8554
> E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: Connection failed
> E/VLC     (12202): [0000007ed17ac510/3266] libvlc stream: VLC could not connect to "192.168.5.87:8554".
> E/VLC     (12202): [0000007ed0f98c90/3266] libvlc input: Your input can't be opened
> E/VLC     (12202): [0000007ed0f98c90/3266] libvlc input: VLC is unable to open the MRL 'rtsp://192.168.5.87:8554/cam'. Check the log for details.
> W/System.err(12202): (flutter_vlc_plugin) A VLC error occurred.
> ```

I have problem, I looked to the logs, and notices, that IOS connecting to Socket as UDP, not TCP

**Comment by rahulbroadview** [comment]
> @jsgalarraga Did you end up getting this working in the emulator too? Sounds like the troubleshooting was done on the real device. I'm having trouble with emulator now. I can confirm my RTSP stream works with VLC (ios/desktop app from VLC), also I'm not seeing my server try to accept any sort of request, so I think I may face similar issue.
> 
> Thanks.

Could you please write you code here, 
RTSP not working in the MacOS when flutter run with desktop,

Thanks in Advance

**Comment by hezhipengzipp** [comment]
D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: creating access: rtsp://192.168.200.1/liveRTSP/av4

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: looking for access module matching "rtsp": 25 candidates

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: try to open 'rtsp://192.168.200.1/liveRTSP/av4'

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: connect to host '192.168.200.1'

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: net: connecting to 192.168.200.1 port 554

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: connection succeeded (socket = 574)

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: net: opening 0.0.0.0 datagram port 9304

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: net: opening 0.0.0.0 datagram port 9305

E/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: Failed to setup RTSP session

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: net: connecting to 192.168.200.1 port 554

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: connection succeeded (socket = 574)

W/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: Cseq mismatch, got 1, assumed 0

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: rtsp connected

W/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: only real/helix rtsp servers supported for now

D/VLC     (14606): [b40000779c8d0220/6deb] libvlc stream: no access modules matched

E/VLC     (14606): [b40000792c824910/6deb] libvlc input: Your input can't be opened

E/VLC     (14606): [b40000792c824910/6deb] libvlc input: VLC is unable to open the MRL 'rtsp://192.168.200.1/liveRTSP/av4'. Check the log for details.

D/VLC     (14606): [b4000078fc893bc0/6def] libvlc demux: connection timeout

E/VLC     (14606): [b4000078fc893bc0/6def] libvlc demux: Failed to connect with rtsp://192.168.200.1:554/liveRTSP/av5

D/VLC     (14606): [b4000078fc893bc0/6def] libvlc demux: no access_demux modules matched

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: creating access: rtsp://192.168.200.1/liveRTSP/av5

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: looking for access module matching "rtsp": 25 candidates

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: try to open 'rtsp://192.168.200.1/liveRTSP/av5'

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: connect to host '192.168.200.1'

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: net: connecting to 192.168.200.1 port 554

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: connection succeeded (socket = 574)

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: net: opening 0.0.0.0 datagram port 9190

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: net: opening 0.0.0.0 datagram port 9191

E/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: Failed to setup RTSP session

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: net: connecting to 192.168.200.1 port 554

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: connection succeeded (socket = 574)

W/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: Cseq mismatch, got 1, assumed 0

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: rtsp connected

W/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: only real/helix rtsp servers supported for now

D/VLC     (14606): [b40000779c8437a0/6def] libvlc stream: no access modules matched

E/VLC     (14606): [b40000792c878360/6def] libvlc input: Your input can't be opened

E/VLC     (14606): [b40000792c878360/6def] libvlc input: VLC is unable to open the MRL 'rtsp://192.168.200.1/liveRTSP/av5'. Check the log for details.
