### ISSUE TITLE
built app is very large size

### ISSUE THREAD

**Issue by ali-1989** [solid-software/flutter_vlc_player#170]
Hi.
I use this player in app, before use it my app size was 9 MB and after use it my app size become 82 MB!!

Flatter 1.22
android SDK 29
Android studio 4.0.1

**Comment by alr2413** [comment]
You included all architectures on the released APK, you can split it for each architecture to reduce output size. 
After that the output size is about 30MB.

https://flutter.dev/docs/deployment/android#building-the-app-for-release

**Comment by ali-1989** [comment]
Thanks, but 30MB is big too.
