### ISSUE TITLE
Tiny Bug on Video Player 

### ISSUE THREAD

**Issue by mitchross** [solid-software/flutter_vlc_player#211]
@solid-software @solid-pavloprykhodko  

I missed a small detail in my PR. Line 91 needs a "!" in front of _isInitialized. This is preventing video form displaying... Probably faster for you to do a one line commit. 

![image](https://user-images.githubusercontent.com/6330506/112248625-9b7c5b00-8c2c-11eb-9d3f-5e4ccbda01bf.png)

**Comment by illia-romanenko** [comment]
fixed that
