### ISSUE TITLE
Reducing Stream Quality

### ISSUE THREAD

**Issue by dianventer** [solid-software/flutter_vlc_player#222]
I am trying to stream multiple RTSP streams on a single page (More than 10).
The app becomes very slow with more than 3 concurrent streams.

I only require one stream to have high resolution outputs and the rest will basically be moving thumbnails.
Is there anyway I can decrease the resolution of the streams to increase the performance of the app?

So far I have adjusted the following in the 'extra' option of the controller:

[
        '--no-embedded-video',
        '--no-audio',
        '--height=160',
        '--width=90',
        '--drop-late-frames',
        '--skip-frames'
      ]

But this does not seem to have an effect on the video streams

**Comment by TungWang** [comment]
Hi! How do you solve this issue. Please help me.
