### ISSUE TITLE
Not able to play song from last stopped location

### ISSUE THREAD

**Issue by Shubham-Phatale** [solid-software/flutter_vlc_player#223]
I am trying to play the video from last location where user stooped the player, but its not working i have tried using controller.seekto() and controller.settime() both are not working please help

function to play song:

void playSong(url) async {
    _videoPlayerController = VlcPlayerController.network(
      url,
      hwAcc: HwAcc.FULL,
      autoInitialize: true,
      autoPlay: false,
      onInit: () async {
        await _videoPlayerController.startRendererScanning();
      },
      onRendererHandler: (type, id, name) {
        print('onRendererHandler $type $id $name');
      },
      options: VlcPlayerOptions(),
    );
    _videoPlayerController.addListener(() {
      if (_videoPlayerController.value.isInitialized) {
        setState(() {
          _duration = _videoPlayerController.value.duration;
          _position = _videoPlayerController.value.position;
          sliderValue = _position.inSeconds.toDouble();
        });
      }
    });
  } 

Pop up in which i ask the user wheather to play from start or continue from last location 
  showPlayDialogue(context, secs) async{
    await showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context){
        return WillPopScope(
          onWillPop: () async => false,
            child:  AlertDialog(
              content: Text('continue from where you stopped?'),
              actions: [
                TextButton(
                    onPressed: (){
                      _videoPlayerController.play();
                                           Navigator.of(context).pop();
                    },
                    child: Text('StartOver')
                ),
                TextButton(
                    onPressed: (){
                      _videoPlayerController.play();
 _videoPlayerController.seekTo(_videoPlayerController.value.position + parseDuration(secs));
                     
 // _videoPlayerController.seekTo(Duration(seconds: 500));
                      Navigator.of(context).pop();
                    },
                    child: Text('Yes')
                )
              ],
            ),
        );
      }
    );
  }

here "secs" is the last location received

**Comment by alr2413** [comment]
you must check the vlc log. 
i think the player is not ready to handle that. put a 1sec delay between play and seek method.

**Comment by Shubham-Phatale** [comment]
it worked man thank you
