### ISSUE TITLE
VLC player Boxfit (Cover,Fill)

### ISSUE THREAD

**Issue by JDPradyut** [solid-software/flutter_vlc_player#229]
I have build a beautiful video player using this flutter vlc player plugin.All I wants to know.Is there any method for Boxfit (Cover, Fill) .I have tried everything but I failed.Please help.By the way Thanks for this awesome video player plugin

**Comment by krunal704** [comment]
Have you tried video scaling?

**Comment by JDPradyut** [comment]
> Have you tried video scaling?

Like?

**Comment by krunal704** [comment]
There is one option to scale up the video. you can call 
controller.setVideoScale(1.3)
This will zoom the video by 1.3x, You can choose the value which suits you best.

**Comment by JDPradyut** [comment]
> There is one option to scale up the video. you can call
> controller.setVideoScale(1.3)
> This will zoom the video by 1.3x, You can choose the value which suits you best.

Thanks for this idea... I'll sure try it. Previously I used Interactive viewer.Where I set Vlc controller aspect ratio to _controller.value.aspectratio.
Thank you again.

**Comment by JDPradyut** [comment]
Finally I solved that issue by my own method.Thanks for helping.

**Comment by Rohithgilla12** [comment]
@JDPradyut Can you say how you did it?
Thanks
