### ISSUE TITLE
The second loading is abnormal

### ISSUE THREAD

**Issue by zjyhll** [solid-software/flutter_vlc_player#237]
When I click the phone physical button to return to the system page, and then click the VLC app to enter

E/flutter (23794): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (23794): #0      VlcPlayerApi.initialize (package:flutter_vlc_player_platform_interface/src/messages/messages.dart:624:7)
E/flutter (23794): <asynchronous suspension>
E/flutter (23794): #1      MethodChannelVlcPlayer.init (package:flutter_vlc_player_platform_interface/src/method_channel/method_channel_vlc_player.dart:34:12)
E/flutter (23794): <asynchronous suspension>
E/flutter (23794): 
E/flutter (23794): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: flutter_video_plugin/getVideoView
E/flutter (23794): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:192)
E/flutter (23794): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (23794): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (23794): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (23794): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (23794): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (23794): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23794): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/flutter (23794): 	at android.os.Looper.loop(Looper.java:175)
E/flutter (23794): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/flutter (23794): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23794): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/flutter (23794): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/flutter (23794): , null, null)
E/flutter (23794): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (23794): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (23794): <asynchronous suspension>
E/flutter (23794): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1043:18)
E/flutter (23794): <asynchronous suspension>
E/flutter (23794): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748:5)
E/flutter (23794): <asynchronous suspension>
E/flutter (23794): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
E/flutter (23794): <asynchronous suspension>

**Comment by VikkyMasih** [comment]
I'm having the same issue. 
Steps to reproduce (using real Android 10 device):
Run example app, play a video, press back button on Android, re-enter app from recents. 
Note: If we kill the process by removing app from recents, then the app works once again.

Main Issue as other errors recover gracefully:  
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

I am new to flutter ecosystem.
I've seen a solution on another plugin (FlutterRadioPlayer) but I'm unable to apply it to this plugin directly. Its occurring because the service is not destroyed on exit.

Please have a look at this:
- https://github.com/Sithira/FlutterRadioPlayer/pull/40
- https://github.com/Sithira/FlutterRadioPlayer/pull/40/commits/a28d9ba09f81162adc136ed6aa59fc6667ebab96

**Comment by KAPILBADWAL** [comment]
Thanks @SurionAndrew ... Worked like a charm. I was stuck on the same issue for a very long time. Many regards. Your prompt response much appreciated.

**Comment by cuongdv25** [comment]
Thanks @SurionAndrew and @zjyhll  I got the same error on Android devices. Now it works like a charm.
