### ISSUE TITLE
how can i add http header to video request?

### ISSUE THREAD

**Issue by SinoMiles** [solid-software/flutter_vlc_player#238]
how can i add http header to video request?
heaser={
  'Referer':'www.xxx.com'
 'User-Agent':'Chrome....'
}

**Comment by alr2413** [comment]
check out the vlc documentation: [https://wiki.videolan.org/VLC_command-line_help/](https://wiki.videolan.org/VLC_command-line_help/)
```
      --http-referrer=<string>   Referrer
          Provide the referral URL, i.e. HTTP "Referer" (sic).
      --http-user-agent=<string> User agent
          Override the name and version of the application as provided to the
          HTTP server, i.e. the HTTP "User-Agent". Name and version must be
          separated by a forward slash, e.g. "FooBar/1.2.3".

```

**Comment by zackattack73** [comment]
@alr2413 It seems like this option is not implemented in the VLC options :
[vlc_advanced_options.dart](https://github.com/solid-software/flutter_vlc_player/blob/master/flutter_vlc_player_platform_interface/lib/src/utils/options/vlc_advanced_options.dart
)
Any plan to add this option soon ?
