### ISSUE TITLE
On release mode app crash

### ISSUE THREAD

**Issue by bilguunint** [solid-software/flutter_vlc_player#28]
App crashed on release mode

**Comment by Michael24884** [comment]
You might want to also post your crash log

> App crashed on release mode

**Comment by soska12** [comment]
Same crash here too.
Log:
2020-03-14 19:28:16.811 23607-23607/? E/VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.example-1/lib/arm/libvlcjni.so"

**Comment by vassilux** [comment]
Hi,
App work good on debug I got crach in release 
this is log 

03-30 11:05:22.497  6679  6679 E VLC/JNI/VLCObject: FindClass(org/videolan/libvlc/Media$Track) failed
03-30 11:05:22.497  6679  6679 E VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.esigroup.spacecontrol-1/lib/arm64/libvlcjni.so"

Any idea

**Comment by soska12** [comment]
> Hi,
> App work good on debug I got crach in release
> this is log
> 
> 03-30 11:05:22.497 6679 6679 E VLC/JNI/VLCObject: FindClass(org/videolan/libvlc/Media$Track) failed
> 03-30 11:05:22.497 6679 6679 E VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.esigroup.spacecontrol-1/lib/arm64/libvlcjni.so"
> 
> Any idea
I managed to solve that issue. Basically it's a flutter side problem, all flutter release mode apps minified and obfuscated by default.
So you have to set 
```
release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }

```
and add proguard rules:
```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class org.videolan.libvlc.** { *; } 
```

After this its working fine for me also in release mode :)

**Comment by vassilux** [comment]
Hi @soska12 ,
Thank for you help it works !!!
