### ISSUE TITLE
Add options to use PlatformViewLink instead of AndroidView

### ISSUE THREAD

**Issue by XuanTung95** [solid-software/flutter_vlc_player#313]
**Actual:**
In my environment `AndroidView` is laggy, `PlatformViewLink` is smooth. [#102492](https://github.com/flutter/flutter/issues/102492)

Currently, it's hard-coded to use `AndroidView`

**Expected:**
Add option to choose between `AndroidView` and `PlatformViewLink`.

It's easy to implement but I think it needs to change this interface (add parameter):

```
  /// Returns a widget displaying the video.
  Widget buildView(PlatformViewCreatedCallback onPlatformViewCreated) {
    throw _unimplemented('buildView');
  }
```

**Comment by illia-romanenko** [comment]
Hi @XuanTung95, feel free to submit a PR, we would be happy to merge it.

**Comment by XuanTung95** [comment]
Please check my PR #314

**Comment by solid-software** [comment]
Merged fix. Thanks for your contribution @XuanTung95 !
