### ISSUE TITLE
Problems to build on iOS and some package issues

### ISSUE THREAD

**Issue by dev-marceloborba** [solid-software/flutter_vlc_player#36]
I was looking for a Flutter package that supports RSTP for my personal project and I found this flutter_vlc_player package on pub.dev.

So, I did install the package on my project, and it worked very well on my Android simulator, but didn't worked on iOS because of some problems during the project compilation.

Then, I went into this github page and I saw a specific note that says about using the flutter_vlc_player class instead of vlc_player (like it was previously showed in pub.dev).

I followed this example on the main page but I think the code is outdated. 

```
import 'package:flutter/material.dart';
import 'package:flutter_vlc_player/flutter_vlc_player.dart';

class ExampleVideo extends StatefulWidget {
  @override
  _ExampleVideoState createState() => _ExampleVideoState();
}

class _ExampleVideoState extends State<ExampleVideo> {
  final String urlToStreamVideo = 'http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4';
  final VlcPlayerController controller = new VlcPlayerController(
      // Start playing as soon as the video is loaded.
      onInit: (){
          controller.play();
      }  
   
// you need to instantiate the controller inside the of the initState life-cycle method

  );
  final int playerWidth = 640; // this variable should be double, not int
  final int playerHeight = 360; // this variable should be double, not int

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SizedBox(
            height: playerHeight,
            width: playerWidth,
            child: new VlcPlayer(
                aspectRatio: 16 / 9,
                url: urlToStreamVideo,
                controller: controller,
                placeholder: Center(child: CircularProgressIndicator()),
            )
        )
    );
  }
}
```

If you copy and paste the code you’ll need to fix some issues to compile the project without errors, but still will not work neither on Android or iOS.

Finally, I did a clone of the example repository and thankfully the project worked on Android and iOS. The first difference that I saw was into the pubspec.yaml file

```
flutter_vlc_player:
    path: ../
```

As we can see, it is referring a path, not a package version. If we change the code to reference the package version (^1.0.0), the project will build without errors, but will show the spinning circle Widget like a infinite loop.

The second difference in the example code that I saw, was into the Podfile on ios folder. Like I said at the beginning, my personal project fails to compile on iOS. Here is my Podfile.

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks! #my personal project have this line
  use_modular_headers! #and also this line

  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

If I comment the use_framewoks! and use_modular_headers! lines my code runs perfectly on iOS.

In resume:

- The example code on pub.dev can work in iOS if you modify the Podfile, but I don’t know if doing this can cause problems to other packages inside the project or performance issues. 

- The example code on github will not work if you change the reference for the flutter_vlc_player package.

- It is an amazing project but I think the examples could be improved. Besides the fact that my project is working, I'm not sure if what I did  is the best solution. It's okay if you need extra configuration on Android and iOS files, but this configuration needs to be very clear.

**Comment by solid-software** [comment]
Hi @dev-marceloborba,

I think most of the problems come from the fact that when you were looking at master you saw not released 2.0.0 version that wasn't available on pub at the time. This version introduces some breaking changes so it's understandable that there are issues in mixing example from pub (^1.0.0) and master (2.0.0). 

2.0.0 is now available on pub - so you can try it now and please let us know how it goes for you.

**Comment by dev-marceloborba** [comment]
Hi @solid-software.

Thanks for the answer.

I created a new project and downloaded the new 2.0.0 version and followed the example on pub.dev.
But unfortunately the code has the same issues that I posted here. You can take a look on the code that I previously posted which I point some problems. A better code is the one posted on example folder here on Github.

So, I did a copy of the main.dart file from the example folder and did a test on my Android simulator. It works! Then I did a test on my iOS simulator. Didn't worked. Still need to manually change the Podfile with exactly the same things that I posted before.

Actually, there’s one more thing to do on the Podfile: uncomment the second line of the file.

```
#Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
...

```

**Comment by solid-software** [comment]
Thanks, we added comment about platform version to the Readme. We'll think about publishing new package to the pub.

**Comment by amadeu01** [comment]
@solid-software I'm facing this problem as well, what is the workaround for this one, do you know?

**Comment by amadeu01** [comment]
I wrote a question in slack for iOS devs. But, I didn't get any answer yet.

Here what I asked. Also, you could help me on this one.

hey folks, I was trying to use a pod that was written in Obj-C and my project is Swift-only. I got this error include of non-modular header inside framework module error  because there is an import inside the framework — that one i’m trying to use — .h  file.
I found some reports about https://github.com/CocoaPods/CocoaPods/issues/8668
https://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework/37125785#37125785
http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
https://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module
It seems like the Module Map  of the project is missing, I want to do a PR to fix this in the library and it allows to work with Swift projects. However, I don’t know how I should configure the podspec of the library.
I’ve seen stuff like in the podspec:
```
s.script_phase = {	
	:name => 'CommonCrypto',	
	:script => 'COMMON_CRYPTO_DIR="${SDKROOT}/usr/include/CommonCrypto"	
	if [ -f "${COMMON_CRYPTO_DIR}/module.modulemap" ]	
		then	
		echo "CommonCrypto already exists, skipping"	
		else	
		# This if-statement means we will only run the main script if the	
		# CommonCrypto.framework directory doesn not exist because otherwise	
		# the rest of the script causes a full recompile for anything	
		# where CommonCrypto is a dependency	
		# Do a "Clean Build Folder" to remove this directory and trigger	
		# the rest of the script to run	
		FRAMEWORK_DIR="${BUILT_PRODUCTS_DIR}/CommonCrypto.framework"	
		if [ -d "${FRAMEWORK_DIR}" ]; then	
			echo "${FRAMEWORK_DIR} already exists, so skipping the rest of the script."	
			exit 0	
		fi	
		mkdir -p "${FRAMEWORK_DIR}/Modules"	
		echo "module CommonCrypto [system] {	
			header \"${SDKROOT}/usr/include/CommonCrypto/CommonCrypto.h\"	
			export *	
		}" >> "${FRAMEWORK_DIR}/Modules/module.modulemap"	
		ln -sf "${SDKROOT}/usr/include/CommonCrypto" "${FRAMEWORK_DIR}/Headers"	
	fi',	
	:execution_position => :before_compile	
  }
```
However , I don’t know how to properly do this.
Should I create a file called ModuleMap.h inside the library /Classes folder? And then put something like below?

```
framework module MixModuleFramework {
  umbrella header "MixModuleFramework.h"
  export *
  module * { export * }
}
```
I don’t want to use the Allow Non-modular Includes in Framework Modules  inside the project. I want to fix the library to its work with other projects.

**Note**: If you run `pod lib lint` you can find the error.

**Note2**: I tried to add a simply bridging header to import the stuff to swift, but with no success.

**Comment by andreidiaconu** [comment]
I am getting the same error. Project is swift, not obj-c.

**Comment by amadeu01** [comment]
I posted a question on cocoapods repo https://github.com/CocoaPods/CocoaPods/issues/9759

**Comment by amadeu01** [comment]
https://github.com/mitchross/flutter_vlc_player 
This folk @mitchross is trying to fix the package to work with swift-only projects.

He opened an issue on VLC https://code.videolan.org/videolan/VLCKit/-/issues/357

**Comment by mitchross** [comment]
Hi @amadeu01  I have the swift conversion done https://github.com/mitchross/flutter_vlc_player/pull/1 ... I have worked with the VLC team and they have added the missing module map. I am waiting for them to fix their CI/CD build to distribute the 3.3.11 cocoa pod here -> https://download.videolan.org/pub/cocoapods/prod/

**Comment by amadeu01** [comment]
@mitchross great work ! I'm also waiting for VLC team to release the 3.3.11 version.

**Comment by amadeu01** [comment]
@mitchross I saw that the version of VLC was released and you merged your PR to swift conversion. Are you planning to open a new PR for this repo?
