### ISSUE TITLE
App crashes in release mode

### ISSUE THREAD

**Issue by alakreasi** [solid-software/flutter_vlc_player#370]
App crashes on launch in release mode, and can't use proguard

**Comment by shameel-zeepalm** [comment]
How did you solve this issue

**Comment by alakreasi** [comment]
Please follow these instructions [https://pub.dev/packages/flutter_vlc_player#android-build-configuration](https://pub.dev/packages/flutter_vlc_player#android-build-configuration)

Delete `minifyEnabled true` and `useProguard true`
