### ISSUE TITLE
How do I set the log level

### ISSUE THREAD

**Issue by front-ck996** [solid-software/flutter_vlc_player#373]
How do I set the log level

**Comment by ctwdtw** [comment]
@front-ck996 I have fewer logs printed on iOS device than on Android device. I suspect it is because log level. I can't find where to set the log level. Seeing you close this issue, did you find the solution?

**Comment by ctwdtw** [comment]
I did not find the interface to set the log level in 7.2.0, but I found it can be set in this file: yourProjectFolder/ios/.symlinks/plugins/flutter_vlc_player/ios/Classes/VlcViewController.swift

```
self.vlcMediaPlayer.libraryInstance.debugLogging = true
self.vlcMediaPlayer.libraryInstance.debugLoggingLevel = 3
```
