### ISSUE TITLE
When I run it says 

### ISSUE THREAD

**Issue by ziasultan2** [solid-software/flutter_vlc_player#4]
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_vlc_player-0.0.2\android\src\main\java\software\solid\fluttervlcplayer\FlutterVideoView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by NBTX** [comment]
You can safely ignore this message, however the issue has been resolved in my Pull Request https://github.com/solid-software/flutter_vlc_player/pull/7
