### ISSUE TITLE
App crash trying play flv via URL on Flutter 3.10.2

### ISSUE THREAD

**Issue by jlopezjuy** [solid-software/flutter_vlc_player#416]
Hello everyone. I have a problem when using VLC with Flutter 3.10.2. When trying to access an FLV file through a URL, the application crashes and closes. However, when testing it from Android Studio connected to the device, no exceptions are shown. Could anyone help me?
```dart
if (widget.urlLiveMobil == 'FLV') {
        String url = 'https://live.gpschile.com/stm/live.flv?devid=' +
            widget.idCamera +
            '&st=1&audio=1&chl=' +
            widget.channel;
        print('---- url');
        print(url);
        _videoPlayerController = VlcPlayerController.network(
          url,
          hwAcc: HwAcc.full,
          autoInitialize: true,
          autoPlay: true,
          options: VlcPlayerOptions(),
        );
      }
      
@override
  Widget build(BuildContext context) {
    final screenHeight = MediaQuery.of(context).size.height;
    final screenWidth = MediaQuery.of(context).size.width;
    return FullScreenWidget(
      disposeLevel: DisposeLevel.High,
      child: Center(
        child: Column(
          children: [
            SizedBox(
              height: 20,
            ),
            Text('Cámara ID: ' + widget.idCamera + ' Canal: ' + widget.channel),
            SizedBox(
              height: 10,
            ),
            errorLocalizado == false
                ? Column(
                    children: [
                      widget.urlLiveMobil == 'M3U8'
                          ? AspectRatio(
                              aspectRatio: 16 / 9,
                              child: BetterPlayer(
                                  controller: _betterPlayerController!),
                            )
                          : VlcPlayer(
                              controller: _videoPlayerController!,
                              aspectRatio: 16 / 9,
                              placeholder:
                                  Center(child: Container(
                                      width: screenWidth,
                                      padding: const EdgeInsets.all(5.0),
                                      child: Center(
                                          child: ColorLoader2(
                                            color1: Color.fromRGBO(121, 121, 121, 1.0),
                                            color2: Color.fromRGBO(255, 231, 80, 1.0),
                                            color3: Color.fromRGBO(26, 66, 138, 1.0),
                                          )))),
                            ),
                    ],
                  )
                : Container(
                    child: Text('Error al obtener video.'),
                  ),
            // this.stream == true
            //     ? Container(
            //         width: screenWidth,
            //         padding: const EdgeInsets.all(5.0),
            //         child: Center(
            //             child: ColorLoader2(
            //           color1: Color.fromRGBO(121, 121, 121, 1.0),
            //           color2: Color.fromRGBO(255, 231, 80, 1.0),
            //           color3: Color.fromRGBO(26, 66, 138, 1.0),
            //         )))
            //     : Container()
          ],
        ),
      ),
    );
  }      

```

**Comment by jlopezjuy** [comment]
The only way I discovered the error was to compile the APK and install on an android, and when using vlc with m3u or another format the application closes, all tested with flutter 3.7.7 and 3.10.2, in the only version that does not pass the error is in flutter 2.10.5.

**Comment by jlopezjuy** [comment]
Hi, this config
```
    packagingOptions {
        // Fixes duplicate libraries build issue,
        // when your project uses more than one plugin that depend on C++ libs.
        pickFirst 'lib/**/libc++_shared.so'
    }
```

Works fine, after add this lines, app dont crash again.

**Comment by ngominhtrungit** [comment]
> It's probably shrinking the app and removing essential files.
> 
> As per the documentation, add this to your `build.gradle`:
> 
> ```
> android {
>     packagingOptions {
>        // Fixes duplicate libraries build issue, 
>        // when your project uses more than one plugin that depend on C++ libs.
>         pickFirst 'lib/**/libc++_shared.so'
>     }
>    
>    buildTypes {
>       release {
>          minifyEnabled true
>          useProguard true
>          proguardFiles getDefaultProguardFile(
>                  'proguard-android-optimize.txt'),
>                  'proguard-rules.pro'
>       }
>    }
> }
> ```
> 
> And add this line to your `android/app/proguard-rules.pro`:
> 
> `-keep class org.videolan.libvlc.** { *; }`
> 
> On another note, how do you localize errors with VLC? I am talking about the `errorLocalizado` in your widget. If you have a workaround for detecting errors, it would be kind to share them in this issue: #410

hi @jlopezjuy , 
I am using flutter version 3.10.4 build `Release` and I have configured gradle,.. with all the instructions available on pub dev of flutter_vlc_player library.

Error: I open android in flick with Android Studio build gradle then error 
`No signature of method: build_fw82v1iv9sixfkei3ejco93z.android() is applicable for argument types: (build_fw82v1iv9sixfkei3ejco93z$_run_closure2) values: [build_fw82v1iv9sixfkei3ejco93z$_run_closure2@328e0c89]`

any help, thanks

**Comment by ngominhtrungit** [comment]
> > It's probably shrinking the app and removing essential files.
> > As per the documentation, add this to your `build.gradle`:
> > ```
> > android {
> >     packagingOptions {
> >        // Fixes duplicate libraries build issue, 
> >        // when your project uses more than one plugin that depend on C++ libs.
> >         pickFirst 'lib/**/libc++_shared.so'
> >     }
> >    
> >    buildTypes {
> >       release {
> >          minifyEnabled true
> >          useProguard true
> >          proguardFiles getDefaultProguardFile(
> >                  'proguard-android-optimize.txt'),
> >                  'proguard-rules.pro'
> >       }
> >    }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And add this line to your `android/app/proguard-rules.pro`:
> > `-keep class org.videolan.libvlc.** { *; }`
> > On another note, how do you localize errors with VLC? I am talking about the `errorLocalizado` in your widget. If you have a workaround for detecting errors, it would be kind to share them in this issue: #410
> 
> hi @jlopezjuy , I am using flutter version 3.10.4 build `Release` and I have configured gradle,.. with all the instructions available on pub dev of flutter_vlc_player library.
> 
> Error: I open android in flick with Android Studio build gradle then error `No signature of method: build_fw82v1iv9sixfkei3ejco93z.android() is applicable for argument types: (build_fw82v1iv9sixfkei3ejco93z$_run_closure2) values: [build_fw82v1iv9sixfkei3ejco93z$_run_closure2@328e0c89]`
> 
> any help, thanks

Hi all, 
after double check and fix error above report by me, folow step below:

1. I downgrade version flutter 3.10.2 (i not yet test 3.10.4, but I think work)
2.  in `build.grade` just add the correct line below:
    >packagingOptions {
       // Fixes duplicate libraries build issue, 
       // when your project uses more than one plugin that depend on C++ libs.
        pickFirst 'lib/**/libc++_shared.so'
   >}

happy with anyone else have problem here. Great day.
