### ISSUE TITLE
How to add a PiP mode?

### ISSUE THREAD

**Issue by LastxTemplar** [solid-software/flutter_vlc_player#460]
Hi,
I noticed that recently there were added some new features like the `allowBackgroundPlayback` option and the `multi-window` support, does this mean we can somehow use the Picture in Picture mode with this player? I just can't find anything useful about this in the documentation at all.

Adding the `allowBackgroundPlayback: true` to the player does indeed keep it playing even if the app goes into the background, but you can only hear the Audio, there is no mini player on the screen, is that something that should be implemented by us or does the player support it somehow?

Thank you!

**Comment by LastxTemplar** [comment]
Anyone has any tips please?

**Comment by LastxTemplar** [comment]
For anyone who is still looking for a solution, I ended up using this package: https://pub.dev/packages/fl_pip.
That package together with the `allowBackgroundPlayback: true` parameter helped me achieve the Picture in Picture feature.

**Comment by wengxianxun** [comment]
> For anyone who is still looking for a solution, I ended up using this package: https://pub.dev/packages/fl_pip. That package together with the `allowBackgroundPlayback: true` parameter helped me achieve the Picture in Picture feature.

how to add vlc to fl_pip , have a sample?
