### ISSUE TITLE
RTSP not working on iPhone with iOS 17

### ISSUE THREAD

**Issue by Spokplacenta** [solid-software/flutter_vlc_player#471]
Hi,

i have this error : 
`Unable to determine our source address: This computer has an invalid IP address: 0.0.0.0`
when i launch video on my iPhone with RTSP, on simulator video is displayed and on my old iPhone 7 with iOS 15 video is displayed too...
in info.plist i have : 
`
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSLocalNetworkUsageDescription</key>
	<string>Used to search for chromecast devices</string>
	<key>NSBonjourServices</key>
	<array>
	<string>_googlecast._tcp</string>
	</array>
`

**Comment by Watss** [comment]
Have you had any response to that?

**Comment by Spokplacenta** [comment]
None, I read that this bug could be linked to: com.apple.developer.networking.multicast
I filled out the Apple form to be eligible, I'm waiting for a response from Apple and I don't know if it will correct my problem...

**Comment by Watss** [comment]
searching, I also came across that answer and I am also requesting this from Apple, thank you very much for the answer

**Comment by MustafaGaber** [comment]
I added com.apple.developer.networking.multicast and still have the problem

**Comment by pradip-android** [comment]
> None, I read that this bug could be linked to: com.apple.developer.networking.multicast I filled out the Apple form to be eligible, I'm waiting for a response from Apple and I don't know if it will correct my problem...

have you got any solution?

**Comment by MustafaGaber** [comment]
> > None, I read that this bug could be linked to: com.apple.developer.networking.multicast I filled out the Apple form to be eligible, I'm waiting for a response from Apple and I don't know if it will correct my problem...
> 
> have you got any solution?

I switched to use media_kit.
It works with rtsp without the need for network entitlement

**Comment by Spokplacenta** [comment]
adding multicast right fixed my problem. 
I tried media-kit but for me, it was less efficient in RTSP. FlutterVlcPlayer 2s delay. MediaKit 3s - 4s delay.

**Comment by Wagkart** [comment]
I tried mdeia kit but the frame gets stuck after 2 seconds and the page needs to be  refreshed to get the latest frame - can you share your media kid configuration?
