### ISSUE TITLE
The release.apk version crashes installing it on the device

### ISSUE THREAD

**Issue by hungnqph07434** [solid-software/flutter_vlc_player#73]
The debug.apk version worked, but the release.apk version crashes installing it on the device

**Comment by mitchross** [comment]
Fix https://github.com/solid-software/flutter_vlc_player/pull/75/files

**Comment by Autokaka** [comment]
Are you encountering this problem only on Android Platform? You need to set code obfuscation (proguard-rules.pro) for your android project like this: 
![image](https://user-images.githubusercontent.com/20894949/87222202-7c8eaf00-c3a4-11ea-8155-f640e7be21bd.png)
The content of `proguard-rules.pro` is:
```
# Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class org.videolan.libvlc.** { *; }
```
Also make sure that in android/app/build.gradle, you should add configs for your release build like this:
![image](https://user-images.githubusercontent.com/20894949/87222301-40a81980-c3a5-11ea-9c5d-7168954c2028.png)
Your problem will be solved after these settings.

**Comment by YulkaPROger** [comment]
Hello. Have you found a solution to the problem? I have a similar situation, proguard-rules.pro did not solve my problem

**Comment by hungnqph07434** [comment]
> Hello. Have you found a solution to the problem? I have a similar situation, proguard-rules.pro did not solve my problem
Have you solved your problem yet ?? If not, you still try proguard-rules.pro and run on real device, 
Build like this: 
![Screen Shot 2020-08-14 at 10 57 20](https://user-images.githubusercontent.com/57426444/90212411-71082b00-de1d-11ea-8e8a-e2b310ea368f.png)

**Comment by YulkaPROger** [comment]
> > Привет. Вы нашли решение проблемы? У меня похожая ситуация, proguard-rules.pro не решил мою проблему 
> > Вы уже решили свою проблему ?? Если нет, вы все равно попробуете proguard-rules.pro и запустите его на реальном устройстве, сделайте 
> > так:
> > ![Снимок экрана 2020-08-14 в 10 57 20](https://user-images.githubusercontent.com/57426444/90212411-71082b00-de1d-11ea-8e8a-e2b310ea368f.png)

Hello I am running flutter run --release on a real device. The application crashes when launching a page with a VLS player widget without errors. If you have any solution to my problem, please help me

**Comment by hungnqph07434** [comment]
> > > Привет. Вы нашли решение проблемы? У меня похожая ситуация, proguard-rules.pro не решил мою проблему
> > > Вы уже решили свою проблему ?? Если нет, вы все равно попробуете proguard-rules.pro и запустите его на реальном устройстве, сделайте
> > > так:
> > > ![Снимок экрана 2020-08-14 в 10 57 20](https://user-images.githubusercontent.com/57426444/90212411-71082b00-de1d-11ea-8e8a-e2b310ea368f.png)
> 
> Hello I am running flutter run --release on a real device. The application crashes when launching a page with a VLS player widget without errors. If you have any solution to my problem, please help me

Can you show me your errors??

**Comment by vikramkapoor** [comment]
I tried the pro-guard changes above but they didn't the crash in release APK. Debug APK works fine but release APK crashes as soon as I try to play any video
