### ISSUE TITLE
sdk: ">=2.1.0 <3.0.0" error

### ISSUE THREAD

**Issue by prakkosal** [solid-software/flutter_vlc_player#8]
flutter sdk: ">=2.1.0 <3.0.0" after installed error project :
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed

**Comment by NBTX** [comment]
@prakkosal You haven't provided enough information. You should always try to at least give the output of `flutter doctor -v` when you submit an issue to any flutter-based resource.
