### ISSUE TITLE
 How can you play 36 rtsp videos with your plugin?) The phone freezes hopelessly ... Please help)

### ISSUE THREAD

**Issue by YulkaPROger** [solid-software/flutter_vlc_player#90]
When I play one or two videos according to your instructions, everything is fine. From 10 - problems begin ... the phone freezes and stops responding.

P.S.: 
I use a google translator, I beg your pardon if it is not translated correctly ...

**Comment by YulkaPROger** [comment]
Sorry, 36 cameras can be viewed on one page, if you set the minimum resolution for 2 stream

**Comment by dianventer** [comment]
@YulkaPROger 

How do you set the resolution?

Warm many thanks.

**Comment by TungWang** [comment]
@YulkaPROger 
Hi! How do you set the resolution?
